/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  elixirsGetElixirs,
  GetElixirsAcceptEnum,
} from "../funcs/elixirsGetElixirs.js";
import {
  elixirsGetElixirsId,
  GetElixirsIdAcceptEnum,
} from "../funcs/elixirsGetElixirsId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetElixirsAcceptEnum } from "../funcs/elixirsGetElixirs.js";

export { GetElixirsIdAcceptEnum } from "../funcs/elixirsGetElixirsId.js";

export class Elixirs extends ClientSDK {
  async getElixirs(
    request: operations.GetElixirsRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetElixirsAcceptEnum },
  ): Promise<operations.GetElixirsResponse> {
    return unwrapAsync(elixirsGetElixirs(
      this,
      request,
      options,
    ));
  }

  async getElixirsId(
    request: operations.GetElixirsIdRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: GetElixirsIdAcceptEnum;
    },
  ): Promise<operations.GetElixirsIdResponse> {
    return unwrapAsync(elixirsGetElixirsId(
      this,
      request,
      options,
    ));
  }
}
