/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  feedbackPostFeedback,
  PostFeedbackAcceptEnum,
} from "../funcs/feedbackPostFeedback.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { PostFeedbackAcceptEnum } from "../funcs/feedbackPostFeedback.js";

export class Feedback extends ClientSDK {
  async postFeedback(
    request?: components.SendFeedbackCommand | undefined,
    options?: RequestOptions & {
      acceptHeaderOverride?: PostFeedbackAcceptEnum;
    },
  ): Promise<operations.PostFeedbackResponse> {
    return unwrapAsync(feedbackPostFeedback(
      this,
      request,
      options,
    ));
  }
}
