/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Elixirs } from "./elixirs.js";
import { Feedback } from "./feedback.js";
import { Houses } from "./houses.js";
import { Ingredients } from "./ingredients.js";
import { Spells } from "./spells.js";
import { Wizards } from "./wizards.js";

export class WizardWorld extends ClientSDK {
  private _elixirs?: Elixirs;
  get elixirs(): Elixirs {
    return (this._elixirs ??= new Elixirs(this._options));
  }

  private _feedback?: Feedback;
  get feedback(): Feedback {
    return (this._feedback ??= new Feedback(this._options));
  }

  private _houses?: Houses;
  get houses(): Houses {
    return (this._houses ??= new Houses(this._options));
  }

  private _ingredients?: Ingredients;
  get ingredients(): Ingredients {
    return (this._ingredients ??= new Ingredients(this._options));
  }

  private _spells?: Spells;
  get spells(): Spells {
    return (this._spells ??= new Spells(this._options));
  }

  private _wizards?: Wizards;
  get wizards(): Wizards {
    return (this._wizards ??= new Wizards(this._options));
  }
}
