/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  GetSpellsAcceptEnum,
  spellsGetSpells,
} from "../funcs/spellsGetSpells.js";
import {
  GetSpellsIdAcceptEnum,
  spellsGetSpellsId,
} from "../funcs/spellsGetSpellsId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetSpellsAcceptEnum } from "../funcs/spellsGetSpells.js";

export { GetSpellsIdAcceptEnum } from "../funcs/spellsGetSpellsId.js";

export class Spells extends ClientSDK {
  async getSpells(
    request: operations.GetSpellsRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetSpellsAcceptEnum },
  ): Promise<operations.GetSpellsResponse> {
    return unwrapAsync(spellsGetSpells(
      this,
      request,
      options,
    ));
  }

  async getSpellsId(
    request: operations.GetSpellsIdRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetSpellsIdAcceptEnum },
  ): Promise<operations.GetSpellsIdResponse> {
    return unwrapAsync(spellsGetSpellsId(
      this,
      request,
      options,
    ));
  }
}
