/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  GetWizardsAcceptEnum,
  wizardsGetWizards,
} from "../funcs/wizardsGetWizards.js";
import {
  GetWizardsIdAcceptEnum,
  wizardsGetWizardsId,
} from "../funcs/wizardsGetWizardsId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetWizardsAcceptEnum } from "../funcs/wizardsGetWizards.js";

export { GetWizardsIdAcceptEnum } from "../funcs/wizardsGetWizardsId.js";

export class Wizards extends ClientSDK {
  async getWizards(
    request: operations.GetWizardsRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetWizardsAcceptEnum },
  ): Promise<operations.GetWizardsResponse> {
    return unwrapAsync(wizardsGetWizards(
      this,
      request,
      options,
    ));
  }

  async getWizardsId(
    request: operations.GetWizardsIdRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: GetWizardsIdAcceptEnum;
    },
  ): Promise<operations.GetWizardsIdResponse> {
    return unwrapAsync(wizardsGetWizardsId(
      this,
      request,
      options,
    ));
  }
}
