/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const FeedbackType = {
  General: "General",
  Bug: "Bug",
  DataError: "DataError",
  Suggestion: "Suggestion",
} as const;
export type FeedbackType = ClosedEnum<typeof FeedbackType>;

/** @internal */
export const FeedbackType$inboundSchema: z.ZodNativeEnum<typeof FeedbackType> =
  z.nativeEnum(FeedbackType);

/** @internal */
export const FeedbackType$outboundSchema: z.ZodNativeEnum<typeof FeedbackType> =
  FeedbackType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FeedbackType$ {
  /** @deprecated use `FeedbackType$inboundSchema` instead. */
  export const inboundSchema = FeedbackType$inboundSchema;
  /** @deprecated use `FeedbackType$outboundSchema` instead. */
  export const outboundSchema = FeedbackType$outboundSchema;
}
