/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetHousesQuery = {};

/** @internal */
export const GetHousesQuery$inboundSchema: z.ZodType<
  GetHousesQuery,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type GetHousesQuery$Outbound = {};

/** @internal */
export const GetHousesQuery$outboundSchema: z.ZodType<
  GetHousesQuery$Outbound,
  z.ZodTypeDef,
  GetHousesQuery
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHousesQuery$ {
  /** @deprecated use `GetHousesQuery$inboundSchema` instead. */
  export const inboundSchema = GetHousesQuery$inboundSchema;
  /** @deprecated use `GetHousesQuery$outboundSchema` instead. */
  export const outboundSchema = GetHousesQuery$outboundSchema;
  /** @deprecated use `GetHousesQuery$Outbound` instead. */
  export type Outbound = GetHousesQuery$Outbound;
}

export function getHousesQueryToJSON(getHousesQuery: GetHousesQuery): string {
  return JSON.stringify(GetHousesQuery$outboundSchema.parse(getHousesQuery));
}

export function getHousesQueryFromJSON(
  jsonString: string,
): SafeParseResult<GetHousesQuery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHousesQuery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHousesQuery' from JSON`,
  );
}
