/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const SpellLight = {
  None: "None",
  Blue: "Blue",
  IcyBlue: "IcyBlue",
  Red: "Red",
  Gold: "Gold",
  Purple: "Purple",
  Transparent: "Transparent",
  White: "White",
  Green: "Green",
  Orange: "Orange",
  Yellow: "Yellow",
  BrightBlue: "BrightBlue",
  Pink: "Pink",
  Violet: "Violet",
  BlueishWhite: "BlueishWhite",
  Silver: "Silver",
  Scarlet: "Scarlet",
  Fire: "Fire",
  FieryScarlet: "FieryScarlet",
  Grey: "Grey",
  DarkRed: "DarkRed",
  Turquoise: "Turquoise",
  PsychedelicTransparentWave: "PsychedelicTransparentWave",
  BrightYellow: "BrightYellow",
  BlackSmoke: "BlackSmoke",
} as const;
export type SpellLight = ClosedEnum<typeof SpellLight>;

/** @internal */
export const SpellLight$inboundSchema: z.ZodNativeEnum<typeof SpellLight> = z
  .nativeEnum(SpellLight);

/** @internal */
export const SpellLight$outboundSchema: z.ZodNativeEnum<typeof SpellLight> =
  SpellLight$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SpellLight$ {
  /** @deprecated use `SpellLight$inboundSchema` instead. */
  export const inboundSchema = SpellLight$inboundSchema;
  /** @deprecated use `SpellLight$outboundSchema` instead. */
  export const outboundSchema = SpellLight$outboundSchema;
}
