/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TraitName = {
  None: "None",
  Courage: "Courage",
  Bravery: "Bravery",
  Determination: "Determination",
  Daring: "Daring",
  Nerve: "Nerve",
  Chivalary: "Chivalary",
  Hardworking: "Hardworking",
  Patience: "Patience",
  Fairness: "Fairness",
  Just: "Just",
  Loyalty: "Loyalty",
  Modesty: "Modesty",
  Wit: "Wit",
  Learning: "Learning",
  Wisdom: "Wisdom",
  Acceptance: "Acceptance",
  Inteligence: "Inteligence",
  Creativity: "Creativity",
  Resourcefulness: "Resourcefulness",
  Pride: "Pride",
  Cunning: "Cunning",
  Ambition: "Ambition",
  Selfpreservation: "Selfpreservation",
} as const;
export type TraitName = ClosedEnum<typeof TraitName>;

/** @internal */
export const TraitName$inboundSchema: z.ZodNativeEnum<typeof TraitName> = z
  .nativeEnum(TraitName);

/** @internal */
export const TraitName$outboundSchema: z.ZodNativeEnum<typeof TraitName> =
  TraitName$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TraitName$ {
  /** @deprecated use `TraitName$inboundSchema` instead. */
  export const inboundSchema = TraitName$inboundSchema;
  /** @deprecated use `TraitName$outboundSchema` instead. */
  export const outboundSchema = TraitName$outboundSchema;
}
